//! Raw FFI bindings to the FFmpeg libraries shipped in the obs-deps bundle
//! (avformat / avcodec / avfilter / avutil). Generated by bindgen at build
//! time from the bundle's own headers, so the bindings can never drift from
//! the runtime obs-express distributes.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
// bindgen emits `transmute` for every bitfield accessor of an enum-typed
// field (AVCodecContext's, here). rustc 1.88's `unnecessary_transmutes` lint
// flags all of them — 10 warnings on every build of generated code we do not
// own and cannot edit. `unknown_lints` keeps older toolchains, which have no
// such lint, quiet about the allow itself.
#![allow(unknown_lints)]
#![allow(unnecessary_transmutes)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Hand-written equivalents of FFmpeg's function-like error macros, which are
// invisible to bindgen (blocklisted in build.rs to guarantee no collision).
// ---------------------------------------------------------------------------

/// `AVERROR(e)`: FFmpeg returns POSIX error codes negated.
pub const fn AVERROR(e: i32) -> i32 {
    -e
}

const fn mktag(a: u8, b: u8, c: u8, d: u8) -> i32 {
    (a as i32) | ((b as i32) << 8) | ((c as i32) << 16) | ((d as i32) << 24)
}

/// `FFERRTAG`: error codes built from four-character tags, negated.
const fn fferrtag(a: u8, b: u8, c: u8, d: u8) -> i32 {
    -mktag(a, b, c, d)
}

pub const AVERROR_EOF: i32 = fferrtag(b'E', b'O', b'F', b' ');
pub const AVERROR_INVALIDDATA: i32 = fferrtag(b'I', b'N', b'D', b'A');
pub const AVERROR_DECODER_NOT_FOUND: i32 = fferrtag(0xF8, b'D', b'E', b'C');

/// `AVERROR(EAGAIN)` with the correct platform errno (11 on Windows/Linux,
/// 35 on macOS).
pub fn averror_eagain() -> i32 {
    AVERROR(libc::EAGAIN)
}

/// `AV_NOPTS_VALUE`: 0x8000000000000000 as int64.
pub const AV_NOPTS_VALUE: i64 = i64::MIN;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_constants_match_ffmpeg() {
        // Known values from FFmpeg's error.h.
        assert_eq!(AVERROR_EOF, -0x2046_4F45); // 'EOF '
        assert_eq!(AVERROR(1), -1);
        assert!(averror_eagain() < 0);
    }

    #[test]
    fn bindings_link_and_report_matching_version() {
        // avcodec 61 is the FFmpeg 7.x line the obs-deps bundle pins.
        let version = unsafe { avcodec_version() };
        assert_eq!(version >> 16, 61, "unexpected libavcodec major: {version}");
    }
}
